/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmBreveRouteImport } from './routes/em-breve'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MedalhasRouteImport } from './routes/medalhas'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as MundoWorldIdRouteImport } from './routes/mundo.$worldId'
import { Route as FaseWorldIdLevelIdRouteImport } from './routes/fase.$worldId.$levelId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmBreveRoute = EmBreveRouteImport.update({
  id: '/em-breve',
  path: '/em-breve',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedalhasRoute = MedalhasRouteImport.update({
  id: '/medalhas',
  path: '/medalhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const MundoWorldIdRoute = MundoWorldIdRouteImport.update({
  id: '/mundo/$worldId',
  path: '/mundo/$worldId',
  getParentRoute: () => rootRouteImport,
} as any)
const FaseWorldIdLevelIdRoute = FaseWorldIdLevelIdRouteImport.update({
  id: '/fase/$worldId/$levelId',
  path: '/fase/$worldId/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/em-breve': typeof EmBreveRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/medalhas': typeof MedalhasRoute
  '/avatar': typeof AvatarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/mundo/$worldId': typeof MundoWorldIdRoute
  '/fase/$worldId/$levelId': typeof FaseWorldIdLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/em-breve': typeof EmBreveRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/medalhas': typeof MedalhasRoute
  '/avatar': typeof AvatarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/mundo/$worldId': typeof MundoWorldIdRoute
  '/fase/$worldId/$levelId': typeof FaseWorldIdLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/em-breve': typeof EmBreveRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/medalhas': typeof MedalhasRoute
  '/avatar': typeof AvatarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/mundo/$worldId': typeof MundoWorldIdRoute
  '/fase/$worldId/$levelId': typeof FaseWorldIdLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/em-breve'
    | '/forgot-password'
    | '/login'
    | '/mapa'
    | '/medalhas'
    | '/avatar'
    | '/reset-password'
    | '/mundo/$worldId'
    | '/fase/$worldId/$levelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/em-breve'
    | '/forgot-password'
    | '/login'
    | '/mapa'
    | '/medalhas'
    | '/avatar'
    | '/reset-password'
    | '/mundo/$worldId'
    | '/fase/$worldId/$levelId'
  id:
    | '__root__'
    | '/'
    | '/em-breve'
    | '/forgot-password'
    | '/login'
    | '/mapa'
    | '/medalhas'
    | '/avatar'
    | '/reset-password'
    | '/mundo/$worldId'
    | '/fase/$worldId/$levelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmBreveRoute: typeof EmBreveRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MedalhasRoute: typeof MedalhasRoute
  AvatarRoute: typeof AvatarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  MundoWorldIdRoute: typeof MundoWorldIdRoute
  FaseWorldIdLevelIdRoute: typeof FaseWorldIdLevelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medalhas': {
      id: '/medalhas'
      path: '/medalhas'
      fullPath: '/medalhas'
      preLoaderRoute: typeof MedalhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-breve': {
      id: '/em-breve'
      path: '/em-breve'
      fullPath: '/em-breve'
      preLoaderRoute: typeof EmBreveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mundo/$worldId': {
      id: '/mundo/$worldId'
      path: '/mundo/$worldId'
      fullPath: '/mundo/$worldId'
      preLoaderRoute: typeof MundoWorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fase/$worldId/$levelId': {
      id: '/fase/$worldId/$levelId'
      path: '/fase/$worldId/$levelId'
      fullPath: '/fase/$worldId/$levelId'
      preLoaderRoute: typeof FaseWorldIdLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmBreveRoute: EmBreveRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MedalhasRoute: MedalhasRoute,
  AvatarRoute: AvatarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  MundoWorldIdRoute: MundoWorldIdRoute,
  FaseWorldIdLevelIdRoute: FaseWorldIdLevelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
